---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.6.0"

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
#  - name: ubuntu-16.04

suites:
  - name: base
    run_list:
      - recipe[stack-base]
    attributes:
