<%
def box_for_provider(distro)
  case ENV.fetch('VAGRANT_DEFAULT_PROVIDER', 'virtualbox')
    when 'virtualbox' then "bento/#{distro}"
    when 'docker' then "tknerr/baseimage-#{distro}"
    else raise 'unsupported provider!'
  end
end
%>
---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.6.0"

platforms:
#  - name: centos-6.7
#    driver_config:
#      box: <%= box_for_provider('ubuntu-12.04') %>
#  - name: centos-7.2
#  - name: debian-7.10
  - name: ubuntu-14.04
    driver_config:
      box: <%= box_for_provider('ubuntu-14.04') %>

suites:
  - name: base
    run_list:
      - recipe[stack-base]
    attributes:
